### ISSUE TITLE
v1.4 - TODO list for version 1.4 release

### ISSUE THREAD

**Issue by mjstealey** [fabric-testbed/fabric-core-api#15]
## Singletons

- [x] GECOS: resolve bastion key NoneType issue - due to empty `oidc_claim_name`
- [x] TAGS: only return project permissions to `facility-operators`, `pc`, `po` and `pm` of that project
- [x] SEARCH: in /people add `family` and `given` names to the search (`email`, `display_name`, `family_name`, `given_name`)
- [x] ROLES: in `/people/{uuid}?as_self=false` do not show roles that link to private projects
- [x] USER: do not optimistically stub user accounts when they log in prior to enrolling through COmanage - it's possible that OIDC claims are not being received as defined by spec and lack attributes to fully stub an account which leads to issues within the existing system

## Referenced issues

- [x] FABlib endpoint: `/testbed-info` - #16 
- [x] EXPIRY: add `vouch_expiry` to whomi output - #14 
- [x] SEARCH: by UUID for people and projects - #13 
- [x] BUGS: and other such things - #12
- [x] LOGS: event logging for metrics - #11 
- [x] TAGS: update project permissions tags - #17

**Comment by mjstealey** [comment]
Deployed on 01/23/2023

- resolves #5 
- resolves #11 
- resolves #12
