### ISSUE TITLE
v1.4.x - placeholder issue for reference

### ISSUE THREAD

**Issue by mjstealey** [fabric-testbed/fabric-core-api#21]
Aggregated issues

- [x] update user - do not update `oidc_claim_sub` as it causes issues with User's that have multiple IdP's using the same email address
- [x] database scripts - export and restore - #7  
- [x] project model alterations - `is_locked`, `expires_on`, logic therein - #19  
- [x] allocated storage volumes - #23 
- [x] add new facility ports for production - #25

**Comment by mjstealey** [comment]
merged and deployed as v1.4.2
