### ISSUE TITLE
v1.6.0 - overview

### ISSUE THREAD

**Issue by mjstealey** [fabric-testbed/fabric-core-api#37]
# v1.6.0

v1.6.0 overview

### v1.6.x GH issues

- [x] long lived tokens (swagger def, endpoints, implementation) (#41)
- [x] expand API endpoints that use token based access (#42)
- [x] user verification endpoint (#43)
- [x] user identity via `sub` (#45)

### additional items

- [x] update documentation for
    - [x] API
    - [x] export and reload scripts
- [x] add `exact_match` parameter to `/people` and `/projects` search 
- [x] remove `publications` endpoints from swagger definition - will become a new independent service (ref #3)
- [x] Update `get_vouch_session_expiry()` in `server/swagger_server/response_code/whoami_utils.py` to allow for Token based expiry
    - currently returns `-1` when using token based auth, which is fine, but needs to be better documented

**Comment by mjstealey** [comment]
merged and deployed
