### ISSUE TITLE
v1.6.2 - minor changes and bug fixes

### ISSUE THREAD

**Issue by mjstealey** [fabric-testbed/fabric-core-api#58]
# v1.6.2 changes and bug fixes

### add expiry date to project list
- [x] add `expires_on` to project list output for projects the user is a creator/owner/member of

### SSH Key - get sliver key for project member
- [x] project members can always retrieve each others ssh sliver public key via API when using tokens if they are members of the same project

## From GH issues

- [x] services authorization check endpoint - #59
- [x] promotional email flag - #60
- [x] project categories - #61 
- [x] update ansible role check - #62 
- [x] Basic core-api metrics - #66
