### ISSUE TITLE
v1.8.0 - release issue tracker

### ISSUE THREAD

**Issue by mjstealey** [fabric-testbed/fabric-core-api#88]
## v1.8.0 issues

- [x] review `whoami` code for delete/create of role reference information 

## tracked by other issues

- [x] #57 - comment when `store_pubkey` is False
- [x] #84 - facility_viewer role

**Comment by mjstealey** [comment]
deployed
